checkpint.dir.jx: "hdfs://nameservice1/spark/checkpoint_jx/"
spark.jx.batch.interval_sec: "5"
kafka.hosts.jx: "183.131.54.162:9092,183.131.54.163:9092,183.131.54.164:9092,183.131.54.165:9092,183.131.54.166:9092"
kafka.topic.jx: "strong-nginx-access"
kafka.groupid.jx: "spark_jx_proc"
kafka.groupid.jx.statis: "spark_jx_proc_band"
es.nodes.jx: "183.136.128.47"
es.port.jx: "9200"

es.nodes.fusion: "183.136.128.47"
es.port.fusion: "9200"
checkpint.dir.fusion:  "hdfs://nameservice1/spark/checkpoint_fusion/"
spark.fcdn.batch.interval_sec: "5"
kafka.hosts.fcdn: "183.131.54.162:9092,183.131.54.163:9092,183.131.54.164:9092,183.131.54.165:9092,183.131.54.166:9092"
kafka.topic.fcdn: "firm_logs"
kafka.groupid.fcdn: "spark_cdn_120"
kafka.groupid.fcdn.statis: "spark_cdn_proc2_statis"